import '../styles/dist.css'
import Providers from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  try{
    const cookie = await fetch('http://localhost:3000/api');
    console.log(cookie.headers.get('token'));
    if(cookie.ok){
        console.log(cookie);
    }else{
        console.log("warning")
    }
  }catch (e){
    console.log(e)
  }
  
  return (
    <html lang="en" data-theme="mytheme">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
      
    </html>
  )
}